export type Language = 'en' | 'hi' | 'mr' | 'bn' | 'te' | 'ta' | 'gu' | 'kn' | 'ml' | 'or' | 'pa' | 'as' | 'mai' | 'bho' | 'har' | 'sat';

export const TRANSLATIONS: Record<Language, any> = {
    en: {
        setup: { title: "NEW GAME SETUP", selectLanguage: "SELECT LANGUAGE", totalPlayers: "TOTAL PLAYERS (1-4)", botCount: "BOTS?", startButton: "START", human: "Human", bot: "Bot" },
        ui: { rolling: "Rolling", moving: "{total} Moving", passedGo: "Passed Go plus 500", landedOn: "Landed on", turn: "Turn", money: "Money", hearts: "Hearts", tapToRoll: "TAP TO ROLL", close: "CLOSE", turnOf: "s Turn", choosing: "Choosing", turnComplete: "Turn complete", result: "Result", done: "Done", wrongAnswer: "Wrong answer One heart lost and 500 penalty", win: "Congratulations {name} has won the game", out: "{name} has lost all hearts and is out of the game", broke: "You are out of funds You need an emergency loan to continue", gameOver: "Game Over {name} is the last one standing and has won", loanSuccess: "Loan of {amount} received from {lender}", welcome: "Welcome to Econopolis 5 Hearts for everyone", weakPin: "Weak PIN Fined 500", strongPin: "Strong PIN Security 20", kycFull: "Grant Approved 2000 Credited", kycBasic: "KYC Verified", upiFail: "Too Easy Your account was hacked 500 lost", upiSuccess: "Strong PIN Your digital wallet is safe", phishingFail: "Scammed You lost money to a con artist 1000 lost", phishingSuccess: "Smart You reported the scam to the bank", quizCorrect: "Correct Knowledge is power", quizWrong: "Wrong You lost 200 for the bad advice", tapperSuccess: "Hard work paid off 1500 earned", atmSuccess: "RD Activated", marketSuccess: "Market was Bullish 500 Gain" },
        miniGames: { kyc: "VERIFY ID", upi: "SECURE YOUR UPI", phishing: "⚠️ SCAM ALERT", quiz: "VILLAGE QUIZ", tapper: "HAUL THE SACKS!", pinAtm: "RD PIN SETUP", marketRisk: "MARKET RISK", scanID: "Scan PAN Card", easyPIN: "Set '1234' (Easy)", strongPIN: "Set '8739' (Strong)", clickScan: "Click Link & Verify", blockScam: "Block & Delete", confirmPIN: "Confirm PIN", rollDice: "ROLL DICE", push: "PUSH!", lenderTitle: "CHOOSE A LENDER", micro: "Micro-Credit", ngo: "NGO Support", shark: "Moneylender" },
        bot: { thinking: ["Reading Scenario...", "Analyzing Risks...", "Calculating ROI...", "Finalizing Choice..."], error: "{name} made a mistake!", done: "{name} completes the task.", chooses: "{name} chooses {choice}" }
    },
    hi: {
        setup: { title: "नया गेम सेटअप", selectLanguage: "भाषा चुनें", totalPlayers: "कुल खिलाड़ी (1-4)", botCount: "बॉट्स?", startButton: "शुरू करें", human: "मानव", bot: "बॉट" },
        ui: { rolling: "घूम रहा है", moving: "{total} चल रहे हैं", passedGo: "गो से गुजरे 500 प्लस", landedOn: "यहाँ पहुँचे", turn: "बारी", money: "पैसे", hearts: "जीवन", tapToRoll: "टैप करें", close: "बंद करें", turnOf: "की बारी", choosing: "चुन रहा है", turnComplete: "बारी पूरी", result: "परिणाम", done: "ठीक है", wrongAnswer: "गलत जवाब एक जीवन खत्म और 500 दंड", win: "बधाई हो {name} ने खेल जीत लिया है", out: "{name} के सभी जीवन खत्म हो गए हैं और वह खेल से बाहर है", broke: "आपके पास पैसे खत्म हो गए हैं जारी रखने के लिए आपको आपातकालीन ऋण की आवश्यकता है", gameOver: "खेल खत्म {name} आखिरी खिलाड़ी बचा है और जीत गया है", loanSuccess: "{lender} से {amount} का ऋण प्राप्त हुआ", welcome: "इकोनोपोलिस में आपका स्वागत है सभी के लिए 5 जीवन", weakPin: "कमजोर पिन 500 का जुर्माना", strongPin: "मजबूत पिन सुरक्षा 20", kycFull: "अनुदान स्वीकृत 2000 जमा किए गए", kycBasic: "KYC सत्यापित", upiFail: "बहुत आसान आपका अकाउंट हैक हो गया 500 खो गए", upiSuccess: "मजबूत पिन आपका डिजिटल वॉलेट सुरक्षित है", phishingFail: "धोखाधड़ी आपने एक जालसाज़ को पैसे खो दिए 1000 खो गए", phishingSuccess: "होशियार आपने बैंक को घोटाले की सूचना दी", quizCorrect: "सही ज्ञान ही शक्ति है", quizWrong: "गलत आपने गलत सलाह के लिए 200 खो दिए", tapperSuccess: "कड़ी मेहनत रंग लाई 1500 कमाए", atmSuccess: "आरडी चालू हो गया", marketSuccess: "बाजार में तेजी थी 500 का लाभ" },
        miniGames: { kyc: "आईडी सत्यापित करें", upi: "UPI सुरक्षित करें", phishing: "⚠️ घोटाला अलर्ट", quiz: "गांव प्रश्नोत्तरी", tapper: "बोरे ढोएं!", pinAtm: "RD पिन सेटअप", marketRisk: "बाजार जोखिम", scanID: "PAN कार्ड स्कैन करें", easyPIN: "1234' सेट करें (आसान)", strongPIN: "'8739' सेट करें (मजबूत)", clickScan: "लिंक पर क्लिक करें", blockScam: "ब्लॉक और डिलीट", confirmPIN: "पिन की पुष्टि करें", rollDice: "पासा फेंके", push: "धक्का!", lenderTitle: "ऋणदाता चुनें", micro: "माइक्रो-क्रेडिट", ngo: "NGO सहायता", shark: "सूदखोर" },
        bot: { thinking: ["परिदृश्य पढ़ रहे हैं...", "जोखिमों का विश्लेषण...", "ROI की गणना...", "विकल्प चुन रहे हैं..."], error: "{name} ने गलती की!", done: "{name} ने काम पूरा किया।", chooses: "{name} {choice} चुनता है" }
    },
    mr: {
        setup: { title: "नवीन गेम सेटअप", selectLanguage: "भाषा निवडा", totalPlayers: "एकूण खेळाडू", botCount: "बॉट्स?", startButton: "सुरू करा", human: "मानव", bot: "बॉट" },
        ui: { rolling: "फिरत आहे", moving: "{total} चालत आहे", passedGo: "गो वरून गेले 500 मिळाले", landedOn: "येथे पोहोचलात", turn: "वेळ", money: "पैसे", hearts: "जीवन", tapToRoll: "टॅप करा", close: "बंद करा", turnOf: "ची वेळ", choosing: "निवडत आहे", turnComplete: "वेळ संपली", result: "निकाल", done: "झाले", wrongAnswer: "चूक उत्तर एक जीवन गमावले आणि 500 दंड", win: "अभिनंदन {name} ने खेळ जिंकला आहे", out: "{name} चे सर्व जीवन संपले आहे आणि तो खेळाबाहेर आहे", broke: "तुमच्याकडे पैसे संपले आहेत पुढे चालू ठेवण्यासाठी तुम्हाला आपत्कालीन कर्जाची गरज आहे", gameOver: "खेळ समाप्त {name} शेवटचा खेळाडू उरला आहे आणि जिंकला आहे", loanSuccess: "{lender} कडून {amount} कर्ज मिळाले", welcome: "इकोनोपोलिसमध्ये आपले स्वागत आहे सर्वांसाठी 5 जीवन", weakPin: "कमकुवत पिन 500 दंड", strongPin: "मजबूत पिन सुरक्षा 20", kycFull: "अनुदान मंजूर 2000 जमा झाले", kycBasic: "KYC पडताळणी यशस्वी", upiFail: "खूप सोपे तुमचे खाते हॅक झाले 500 गमावले", upiSuccess: "मजबूत पिन तुमचे digital वॉलेट सुरक्षित आहे", phishingFail: "फसवणूक तुम्ही फसवणुकीत पैसे गमावले 1000 गमावले", phishingSuccess: "हुशार तुम्ही बँकेला घोटाळ्याची माहिती दिली", quizCorrect: "बरोबर ज्ञान हीच शक्ती आहे", quizWrong: "चूक चुकीच्या सल्ल्यामुळे तुम्ही 200 गमावले", tapperSuccess: "कष्ट फळाला आले 1500 कमावले", atmSuccess: "आरडी सुरू झाले", marketSuccess: "बाजार तेजीत होता 500 चा फायदा" },
        miniGames: { kyc: "आयडी पडताळणी", upi: "UPI सुरक्षित करा", phishing: "⚠️ घोटाळा चेतावणी", quiz: "गाव प्रश्नमंजुषा", tapper: "पोती उचला!", pinAtm: "RD पिन सेटअप", marketRisk: "बाजार जोखीम", scanID: "PAN कार्ड स्कॅन करा", easyPIN: "'1234' सेट करा (सोपे)", strongPIN: "'8739' सेट करा (मजबूत)", clickScan: "लिंकवर क्लिक करा", blockScam: "ब्लॉक आणि डिलीट", confirmPIN: "पिन पुष्टी करा", rollDice: "फासा फेका", push: "ढकल!", lenderTitle: "कर्जदार निवडा", micro: "मायक्रो-क्रेडिट", ngo: "NGO आधार", shark: "सावकार" },
        bot: { thinking: ["परिस्थिती वाचत आहे...", "जोखीम विश्लेषण...", "फायदा मोजत आहे...", "शेवटचा निर्णय..."], error: "{name} ने चूक केली!", done: "{name} ने काम पूर्ण केले.", chooses: "{name} {choice} निवडत आहे" }
    },
    bn: {
        setup: { title: "নতুন গেম সেটআপ", totalPlayers: "মোট খেলোয়াড়", botCount: "বট?", startButton: "শুরু করুন", human: "মানুষ", bot: "বট" },
        ui: { rolling: "ঘুরছে", moving: "যাচ্ছে", passedGo: "500 টাকা পেলেন", landedOn: "এখানে পৌঁছেছেন", turn: "পালা", money: "টাকা", hearts: "জীবন", tapToRoll: "ট্যাপ করুন", close: "বন্ধ করুন", turnOf: "এর পালা", choosing: "বেছে নিচ্ছে", turnComplete: "পালা শেষ", result: "ফলাফল", done: "ঠিক আছে" },
        miniGames: { kyc: "আইডি যাচাই", upi: "UPI সুরক্ষিত করুন", phishing: "⚠️ প্রতারণা সতর্কতা", quiz: "গ্রাম ক্যুইজ", tapper: "বস্তা টানুন!", pinAtm: "RD পিন সেটআপ", marketRisk: "বাজার ঝুঁকি", scanID: "PAN কার্ড স্ক্যান করুন", easyPIN: "'1234' সেট করুন (সহজ)", strongPIN: "'8739' সেট করুন (শক্তিশালী)", clickScan: "লিঙ্ক ক্লিক করুন", blockScam: "ব্লক ও ডিলিট", confirmPIN: "পিন নিশ্চিত করুন", rollDice: "ছক্কা দান দিন", push: "ঠেুন!", lenderTitle: "ঋণদাতা বাছুন", micro: "মাইক্রো-ক্রেডিট", ngo: "NGO সহায়তা", shark: "মহাজন" },
        bot: { thinking: ["পরিস্থিতি পড়ছে...", "ঝুঁকি বিশ্লেষণ...", "লাভ গণনা...", "শেষ সিদ্ধান্ত..."], error: "ভুল করল!", done: "কাজ শেষ করল।" }
    },
    te: {
        setup: { title: "కొత్త గేమ్ సెటప్", totalPlayers: "మొత్తం ప్లేయర్స్", botCount: "బాట్‌లు?", startButton: "మొదలు", human: "మనిషి", bot: "బాట్" },
        ui: { rolling: "తిరుగుతోంది...", moving: "వెళ్తోంది...", passedGo: "+500 జీతం", landedOn: "ఇక్కడ ఆగారు:", turn: "వంతు", money: "డబ్బు", hearts: "గుండెలు", tapToRoll: "టాప్ చేయండి", close: "మూసివేయి", turnOf: "వంతు", choosing: "ఎంచుకుంటోంది...", turnComplete: "వంతు పూర్తయింది.", result: "ఫలితం", done: "పూర్తి" },
        miniGames: { kyc: "ఐడి వెరిఫై", upi: "UPI సెక్యూరిటీ", phishing: "⚠️ స్కామ్ అలర్ట్", quiz: "విలేజ్ క్విజ్", tapper: "బస్తాలు మోయండి!", pinAtm: "RD పిన్ సెటప్", marketRisk: "మార్కెట్ రిస్క్", scanID: "PAN కార్డ్ స్కాన్ చేయండి", easyPIN: "'1234' సెట్ చేయండి (సులభం)", strongPIN: "'8739' సెట్ చేయండి (బలంగా)", clickScan: "లింక్ క్లిక్ చేయండి", blockScam: "బ్లాక్ & డిలీట్", confirmPIN: "పిన్ నిర్ధారించండి", rollDice: "పాచికలు వేయండి", push: "నెట్టండి!", lenderTitle: "రుణదాతను ఎంచుకోండి", micro: "మైక్రో-క్రెడిట్", ngo: "NGO సహాయం", shark: "వడ్డీ వ్యాపారి" },
        bot: { thinking: ["పరిస్థితిని చదవడం...", "ప్రమాదాల విశ్లేషణ...", "ROI లెక్కింపు...", "నిర్ణయం తీసుకోవడం..."], error: "తప్పు చేశాడు!", done: "పని పూర్తి చేశాడు." }
    },
    ta: {
        setup: { title: "புதிய விளையாட்டு", totalPlayers: "வீரர்கள்", botCount: "பாட்கள்?", startButton: "தொடங்கு", human: "மனிதன்", bot: "பாட்" },
        ui: { rolling: "சுழல்கிறது...", passedGo: "+500 சம்பளம்", landedOn: "இங்கே வந்தீர்கள்:", turn: "முறை", money: "பணம்", hearts: "உயிர்கள்", tapToRoll: "தட்டவும்", close: "மூடு", turnOf: "இன் முறை", choosing: "தேர்ந்தெடுக்கிறது...", turnComplete: "முறை முடிந்தது.", result: "முடிவு", done: "சரி" }
    },
    gu: {
        setup: { title: "નવી ગેમ સેટઅપ", totalPlayers: "કુલ ખેલાડીઓ", botCount: "બોટ્સ?", startButton: "શરૂ કરો", human: "માનવ", bot: "બોટ" },
        ui: { rolling: "ફરે છે", moving: "{total} ચાલે છે", passedGo: "ગો પાસ કર્યું 500 મળ્યા", landedOn: "અહીં પહોંચ્યા", turn: "વારો", money: "પૈસા", hearts: "જીવન", tapToRoll: "ટેપ કરો", close: "બંધ કરો", turnOf: "નો વારો", choosing: "પસંદ કરે છે", turnComplete: "વારો પૂરો થયો", result: "પરિણામ", done: "થઈ ગયું", wrongAnswer: "ખોટો જવાબ એક જીવન ગુમાવ્યું અને 500 દંડ", win: "અભિનંદન {name} રમત જીતી ગયા છે", out: "{name} ના બધા જીવન પૂરા થઈ ગયા છે અને તે રમતની બહાર છે", broke: "તમારી પાસે પૈસા પૂરા થઈ ગયા છે આગળ વધવા માટે તમારે લોનની જરૂર છે", gameOver: "રમત પૂરી {name} છેલ્લે બચ્યા છે અને જીતી ગયા છે", loanSuccess: "{lender} પાસેથી {amount} લોન મળી", welcome: "ઇકોનોપોલિસમાં તમારું સ્વાગત છે બધા માટે 5 જીવન", weakPin: "નબળો પિન 500 દંડ", strongPin: "મજબૂત પિન સુરક્ષા 20", kycFull: "ગ્રાન્ટ મંજૂર 2000 જમા થયા", kycBasic: "KYC સફળતાપૂર્વક પૂર્ણ થયું", upiFail: "ખૂબ જ સરળ તમારું એકાઉન્ટ હેક થઈ ગયું 500 ગયા", upiSuccess: "મજબૂત પિન તમારું ડિજિટલ વૉલેટ સુરક્ષિત છે", phishingFail: "છેતરપિંડી તમે છેતરપિંડીમાં પૈસા ગુમાવ્યા 1000 ગયા", phishingSuccess: "સમજદારી તમે બેંકને ફ્રોડની જાણ કરી", quizCorrect: "સાચું જ્ઞાન જ શક્તિ છે", quizWrong: "ખોટું ખોટી સલાહ બદલ તમે 200 ગુમાવ્યા", tapperSuccess: "મહેનત ફળી 1500 કમાણી", atmSuccess: "આરડી શરૂ થઈ ગયું", marketSuccess: "બજાર તેજીમાં હતું 500 ફાયદો" },
        miniGames: { kyc: "આઈડી વેરિફાઈ", upi: "UPI સુરક્ષિત કરો", phishing: "⚠️ છેતરપિંડી એલર્ટ", quiz: "ગામ ક્વિઝ", tapper: "કોથળા ઉપાડો!", pinAtm: "RD પિન સેટઅપ", marketRisk: "બજાર જોખમ", scanID: "PAN કાર્ડ સ્કેન કરો", easyPIN: "'1234' સેટ કરો (સરળ)", strongPIN: "'8739' સેટ કરો (મજબૂત)", clickScan: "લિંક પર ક્લિક કરો", blockScam: "બ્લોક અને ડિલીટ", confirmPIN: "પિન કન્ફર્મ કરો", rollDice: "પાસા ફેંકો", push: "ધક્કો!", lenderTitle: "લોન આપનાર પસંદ કરો", micro: "માઇક્રો-ક્રેડિટ", ngo: "NGO મદદ", shark: "વ્યાજખોર" },
        bot: { thinking: ["પરિસ્થિતિ વાંચી રહ્યા છે...", "જોખમ વિશ્લેષણ...", "ROI ગણતરી...", "નિર્ણય લઈ રહ્યા છે..."], chooses: "{name} {choice} પસંદ કરે છે", error: "{name} એ ભૂલ કરી!", done: "{name} એ કામ પૂરું કર્યું." }
    },
    kn: {
        setup: { title: "ಹೊಸ ಆಟದ ಸೆಟಪ್", totalPlayers: "ಒಟ್ಟು ಆಟಗಾರರು", botCount: "ಬೋಟ್‌ಗಳು?", startButton: "ಪ್ರಾರಂಭಿಸಿ", human: "ಮಾನವ", bot: "ಬೋಟ್" },
        ui: { rolling: "ಉರುಳುತ್ತಿದೆ...", passedGo: "+500 ವೇತನ", landedOn: "ಇಲ್ಲಿ ತಲುಪಿದಿರಿ:", turn: "ಸರದಿ", money: "ಹಣ", hearts: "ಜೀವಗಳು", tapToRoll: "ಟ್ಯಾಪ್ ಮಾಡಿ", close: "ಮುಚ್ಚಿ", turnOf: "ಅವರ ಸರದಿ", choosing: "ಆರಿಸುತ್ತಿದೆ...", turnComplete: "ಸರದಿ ಮುಗಿದಿದೆ.", result: "ಫಲಿತಾಂಶ", done: "ಆಯಿತು" }
    },
    ml: {
        setup: { title: "പുതിയ ഗെയിം സെറ്റപ്പ്", totalPlayers: "കളിക്കാർ", botCount: "ബോട്ടുകൾ?", startButton: "തുടങ്ങുക", human: "മനുഷ്യൻ", bot: "ബോട്ട്" },
        ui: { rolling: "ഉരുളുന്നു...", passedGo: "+500 ശമ്പളം", landedOn: "ഇവിടെ എത്തി:", turn: "ഊഴം", money: "പണം", hearts: "ജീവൻ", tapToRoll: "ടാപ്പ് ചെയ്യുക", close: "അടയ്ക്കുക", turnOf: "ന്റെ ഊഴം", choosing: "തിരഞ്ഞെടുക്കുന്നു...", turnComplete: "ഊഴം കഴിഞ്ഞു.", result: "ഫലം", done: "ശരി" }
    },
    or: {
        setup: { title: "ନୂଆ ଗେମ୍ ସେଟଅପ୍", totalPlayers: "ମୋଟ ଖେଳାଳି", botCount: "ବଟ୍?", startButton: "ଆରମ୍ଭ", human: "ମଣିଷ", bot: "ବଟ୍" },
        ui: { rolling: "ବୁଲୁଛି...", passedGo: "+500 ଦରମା", landedOn: "ଏଠି ପହଞ୍ଚିଲେ:", turn: "ପାଳି", money: "ଟଙ୍କା", hearts: "ଜୀବନ", tapToRoll: "ଟ୍ୟାପ୍ କରନ୍ତୁ", close: "ବନ୍ଦ କରନ୍ତୁ", turnOf: "ଙ୍କ ପାଳି", choosing: "ବାଛୁଛି...", turnComplete: "ପାଳି ସରିଲା।", result: "ଫଳାଫଳ", done: "ହେଲା" }
    },
    pa: {
        setup: { title: "ਨਵੀਂ ਗੇਮ ਸੈਟਅਪ", totalPlayers: "ਕੁੱਲ ਖਿਡਾਰੀ", botCount: "ਬੋਟ?", startButton: "ਸ਼ੁਰੂ ਕਰੋ", human: "ਇਨਸਾਨ", bot: "ਬੋਟ" },
        ui: { rolling: "ਘੁੰਮ ਰਿਹਾ...", passedGo: "+500 ਤਨਖਾਹ", landedOn: "ਇੱਥੇ ਪਹੁੰਚੇ:", turn: "ਵਾਰੀ", money: "ਪੈਸੇ", hearts: "ਜਾਨ", tapToRoll: "ਟੈਪ ਕਰੋ", close: "ਬੰਦ ਕਰੋ", turnOf: "ਦੀ ਵਾਰੀ", choosing: "ਚੁਣ ਰਿਹਾ ਹੈ...", turnComplete: "ਵਾਰੀ ਪੂਰੀ ਹੋਈ।", result: "ਨਤੀਜਾ", done: "ਠੀਕ ਹੈ" }
    },
    as: {
        setup: { title: "নতুন খেলৰ ব্যৱস্থা", totalPlayers: "মুঠ খেলুৱৈ", botCount: "বট?", startButton: "আৰম্ভ", human: "মানুহ", bot: "বট" },
        ui: { rolling: "ঘূৰি আছে...", passedGo: "+500 দৰমহা", landedOn: "ইয়াত উপস্থিত হৈছে:", turn: "পাল", money: "টকা", hearts: "জীৱন", tapToRoll: "টিপক", close: "বন্ধ কৰক", turnOf: "ৰ পাল", choosing: "বাছি আছে...", turnComplete: "পাল শেষ হ’ল।", result: "ফলাফল", done: "হ’ল" }
    },
    mai: {
        setup: { title: "नया गेम सेटअप", totalPlayers: "कुल खिलाड़ी", botCount: "बोट?", startButton: "शुरू करू", human: "मानुष", bot: "बोट" },
        ui: { rolling: "घूम रहल अछि...", passedGo: "+500 वेतन", landedOn: "एतय पहुँचलहुँ:", turn: "बारी", money: "टका", hearts: "जीन", tapToRoll: "टैप करू", close: "बंद करू", turnOf: "क बारी", choosing: "चुन रहल अछि...", turnComplete: "बारी पूरा भेल।", result: "परिणाम", done: "भ गेल" }
    },
    bho: {
        setup: { title: "नया खेल सेटअप", totalPlayers: "कुल खिलाड़ी", botCount: "बोट?", startButton: "चालू करीं", human: "आदमी", bot: "बोट" },
        ui: { rolling: "घूम रहल बा...", passedGo: "+500 पगार", landedOn: "हिँवा पहुँचल बा:", turn: "बारी", money: "रुपिया", hearts: "जान", tapToRoll: "टैप करीं", close: "बंद करीं", turnOf: "के बारी", choosing: "चुन रहल बा...", turnComplete: "बारी पूरा भइल।", result: "नतीजा", done: "हो गइल" }
    },
    har: {
        setup: { title: "नया खेल सैटअप", totalPlayers: "कुल खिलाड़ी", botCount: "बोट?", startButton: "शुरू करो", human: "माणस", bot: "बोट" },
        ui: { rolling: "घूम रह्या सै...", passedGo: "+500 तनखा", landedOn: "उड़ै पहुँच गया:", turn: "बारी", money: "रुपैया", hearts: "जी", tapToRoll: "टैप करो", close: "बंद करो", turnOf: "की बारी", choosing: "सांट रह्या सै...", turnComplete: "बारी पूरी होग्यी।", result: "नतीजा", done: "होग्या" }
    },
    sat: {
        setup: { title: "नवा खेल सेटअप", totalPlayers: "जतो खिलाड़ी", botCount: "बोट?", startButton: "एतोब", human: "होड़", bot: "बोट" },
        ui: { rolling: "अच्युरो काना...", passedGo: "+500 तलप", landedOn: "नण्डे सेटेर", turn: "वारा", money: "टका", hearts: "जीवि", tapToRoll: "टैप मे", close: "बंध मे", turnOf: "या: वारा", choosing: "बाछाव एदा...", turnComplete: "वारा मुचात ना।", result: "रिज़ल्ट", done: "हुय ना" }
    }
};
